import 'package:get/get.dart';

import '../app_config.dart';

class AppLocalization implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          AppConfig.phone: "رقم الهاتف",
          AppConfig.exitApp: "الخروج من التطبيق",
          AppConfig.descreiption: "الوصف",
          AppConfig.settings: "الاعدادات",
          AppConfig.suggested: "الاقتراحات",
          AppConfig.updatDataUser: "تم تحديث البيانات بنجاح.",
          AppConfig.editYourProfile: "تعديل الملف الشخصي",
          AppConfig.agreeTotermsOfServices:
              "من خلال التسجيل في التطبيق، فإنك توافق على",
          AppConfig.delete: "حذف",
          AppConfig.forgotPassword: "نسيت كلمة المرور",
          AppConfig.email: "البريد الالكتروني",
          AppConfig.profile: "الملف الشخصي",
          AppConfig.addTicket: "اضافة تدكرة",
          AppConfig.signUpWithEmail: "التسجيل عن طريق البريد الإلكتروني",
          AppConfig.timeOut: "يبدو ان اتصال الانترنت لديك ضعيف",
          AppConfig.tryAgain: "اعادة المحاولة",
          AppConfig.login: "تسجيل الدخول",
          AppConfig.chooseCategory: "",
          AppConfig.history: "السجل",
          AppConfig.reviews: "التقييمات",
          AppConfig.faq: "الأسئلة الشائعة",
          AppConfig.logout: "تسجيل الخروج",
          AppConfig.emiratesID: AppConfig.emiratesID,
          AppConfig.hidePassword: "اخفاء كلمة المرور",
          AppConfig.privacyPolicy: "سياسة الخصوصية",
          AppConfig.termsOfService: "الشروط والأحكام",
          AppConfig.version: "الاصدار",
          AppConfig.search: "بحث",
          AppConfig.searchByName: "ابحث بالمشروع او الشقة او المتجمع الخ...",
          AppConfig.seeAll: "عرض الكل",
          AppConfig.aboutApp: "حول التطبيق",
          AppConfig.ok: "موافق",
          AppConfig.success: "نجاح",
          AppConfig.selectLanguage: "اختار اللغة",
          AppConfig.selectGender: "حدد الجنس",
          AppConfig.pleaseEnterEmail: "يجب ادخال البريد الالكتروني",
          AppConfig.pleaseEnteremiratesID: "يجب ادخال رقم الهوية ",
          AppConfig.enterYourPassword: "يجب ادخال كلمة المرور",
          AppConfig.enterYourUserName: "يجب ادخال اسم المستخدم",
          AppConfig.confairmPassword: "يجب تأكيد كلمة المرور",
          AppConfig.alert: "تنبية",
          AppConfig.inDelivering: "جارى التوصيل",
          AppConfig.isDelivered: "تم التسليم",
          AppConfig.yes: "نعم",
          AppConfig.no: "لا",
          AppConfig.noInternet: "لايوجد اتصال بالانترنت",
          AppConfig.cancel: "الغاء",
          AppConfig.somthimgWroing: "حدث خطأ",
          AppConfig.fullName: "الاسم بالكامل",
          AppConfig.contenue: "متابعة",
          AppConfig.save: "حفظ",
          AppConfig.offers: "العروض",
          AppConfig.AllNotifcation: "كل الاشعارات",
          AppConfig.resetPassword: "استعادة كلمة المرور",
          AppConfig.wasReceived: "تم الاستلام",
          AppConfig.password: "كلمة المرور",
          AppConfig.enterYourPhone: "ادخل رقم الهاتف",
          AppConfig.userName: "اسم المستخدم",
          AppConfig.allFaildRequired: "جميع الحقول مطلوبة",
          AppConfig.notifcation: "الاشعارات",
          AppConfig.security: "الأمان",
          AppConfig.contactUs: "تواصل معنا",
          AppConfig.myPortofolio: "مشاريعي",
          AppConfig.next: "متابعة",
          AppConfig.portofolio: "مشاريعي",
          AppConfig.active: "نشطة",
          AppConfig.completed: "مكتملة",
          AppConfig.helpCenter: "الدعم الفني",
          AppConfig.listings: "المنشورات",
          AppConfig.addNewListing: "اضافة مشروع جديد",
          AppConfig.sold: "Sold",
          AppConfig.defultFilter: 'الكل',
          AppConfig.sortBy: "ترتيب حسب",
          AppConfig.rent: "ايجار",
          AppConfig.sell: "بيع",
          AppConfig.language: "اللغة",
        },
        "en": {
          AppConfig.ok: "OK",
          AppConfig.userName: AppConfig.userName,
          AppConfig.addNewListing: AppConfig.addNewListing,
          AppConfig.suggested: AppConfig.suggested,
          AppConfig.sortBy: AppConfig.sortBy,
          AppConfig.rent: AppConfig.rent,
          AppConfig.sell: AppConfig.sell,
          AppConfig.security: AppConfig.security,
          AppConfig.active: AppConfig.active,
          AppConfig.completed: AppConfig.completed,
          AppConfig.sold: AppConfig.sold,
          AppConfig.listings: AppConfig.listings,
          AppConfig.addTicket: AppConfig.addTicket,
          AppConfig.portofolio: AppConfig.portofolio,
          AppConfig.myPortofolio: AppConfig.myPortofolio,
          AppConfig.next: AppConfig.next,
          AppConfig.password: AppConfig.password,
          AppConfig.notifcation: AppConfig.notifcation,
          AppConfig.contactUs: AppConfig.contactUs,
          AppConfig.faq: AppConfig.faq,
          AppConfig.profile: AppConfig.profile,
          AppConfig.yes: AppConfig.yes,
          AppConfig.no: AppConfig.no,
          AppConfig.defultFilter: AppConfig.defultFilter,
          AppConfig.offers: AppConfig.offers,
          AppConfig.language: AppConfig.language,
          AppConfig.pleaseEnteremiratesID: AppConfig.pleaseEnteremiratesID,
          AppConfig.emiratesID: AppConfig.emiratesID,
          AppConfig.helpCenter: AppConfig.helpCenter,
          AppConfig.searchByName: AppConfig.searchByName,
          AppConfig.updatDataUser: AppConfig.updatDataUser,
          AppConfig.logout: AppConfig.logout,
          AppConfig.settings: AppConfig.settings,
          AppConfig.noInternet: AppConfig.noInternet,
          AppConfig.selectLanguage: AppConfig.selectLanguage,
          AppConfig.forgotPassword: AppConfig.forgotPassword,
          AppConfig.success: AppConfig.success,
          AppConfig.termsOfService: AppConfig.termsOfService,
          AppConfig.hidePassword: AppConfig.hidePassword,
          AppConfig.AllNotifcation: AppConfig.AllNotifcation,
          AppConfig.resetPassword: "Reset Password"
        },
      };
}
/* 


*/